# Generated by Django 4.1.1 on 2022-10-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_answers_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='image',
            new_name='file',
        ),
    ]
