# Generated by Django 4.1.1 on 2022-10-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_rename_image_question_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='defendant_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='defendant_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='defendant_surname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='prosecutor_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='prosecutor_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='prosecutor_parent_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='prosecutor_parent_pesel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='prosecutor_parent_surname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='prosecutor_pesel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='prosecutor_surname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
