# Generated by Django 4.1.1 on 2022-10-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_question_file_remove_question_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='defendant_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='defendant_surname',
        ),
        migrations.RemoveField(
            model_name='question',
            name='prosecutor_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='prosecutor_surname',
        ),
        migrations.AddField(
            model_name='question',
            name='defendant_name_surname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='prosecutor_name_surname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
