# Generated by Django 4.1.1 on 2022-10-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_question_defendant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lawsuit_1_prosecutor_price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
